added code
Romanucci/aleksey_romanov pull request #2
Opened 2022-09-29 11:26 UTC by Romanucci

2022-10-04 13:16 UTC, MarinaPaley requested changes
Посмотрите в сторону [тестов](https://github.com/MarinaPaley/DataBaseManagementSystem/blob/feature/5/VectorExample/Tests/Tests.cpp).

2022-10-06 12:08 UTC, MarinaPaley requested changes

2022-10-06 12:08 UTC, MarinaPaley commented on DinamicDecMassive.h
> +	IntegerMatrix(const unsigned int, const unsigned int);
`const int`

2022-10-06 12:08 UTC, MarinaPaley commented on DinamicDecMassive.h
> +	~IntegerMatrix();
[Правило_пяти](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D1%82%D1%80%D1%91%D1%85_(C%2B%2B)#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D0%BF%D1%8F%D1%82%D0%B8)

2022-10-10 18:05 UTC, Romanucci commented on DinamicDecMassive.cpp
> +int const IntegerMatrix::get_elem(unsigned int i, unsigned int j) {
Это не единственный способ использования operator[][]. При перегрузке operator[][] какие-то функции могут работать некорректно, например, в функции fill_rnd интервал значений сместится влево на единицу

2022-10-12 16:28 UTC, MarinaPaley commented on DinamicDecMassive.cpp
> +int const IntegerMatrix::get_elem(unsigned int i, unsigned int j) {
жаль(

2022-10-27 13:20 UTC, MarinaPaley requested changes

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +
Пустая строка лишняя

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +    for (size_t row = 0; row < rows; row++) {
Массив необходимо удалять следующим безопасным способом
```cpp
if (array != nullptr)
{
   delete[] array;
   array = nullptr;
}
```

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +void del_matrix(int** ptr, size_t rows) {
`int**& ptr...`

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +    std::uniform_int_distribution<> uniform_int_distribution(-20, 20);
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +        std::cout << local_max << std::endl;
никаких связей с потоками ввода вывода

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +void task_1(int** ptr, size_t rows, size_t columns) {
отдавайте новый массив

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +        throw std::range_error("Only positive values!");
В `main` только ловим ошибки

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +    std::cout << "2 - fill manual" << std::endl;
[Магичесикие константы](https://github.com/MarinaPaley/Demo-CPP/blob/master/Task%204-1/main.cpp#L149)

2022-10-27 13:20 UTC, MarinaPaley commented on main.cpp
> +
удаление массивов (всех)
`return 0`

2022-10-27 13:35 UTC, Romanucci commented on main.cpp
> +int** set_matrix(int rows, int columns) {
done!

2022-10-27 13:36 UTC, Romanucci commented on main.cpp
> +
done!

2022-10-27 13:45 UTC, Romanucci commented on main.cpp
> +    for (size_t row = 0; row < rows; row++) {
done!

2022-10-27 13:45 UTC, Romanucci commented on main.cpp
> +void del_matrix(int** ptr, size_t rows) {
done!

2022-10-27 13:54 UTC, Romanucci commented on main.cpp
> +    std::uniform_int_distribution<> uniform_int_distribution(-20, 20);
done!

2022-10-27 13:55 UTC, Romanucci commented on main.cpp
> +        std::cout << local_max << std::endl;
done!

2022-10-27 14:03 UTC, Romanucci commented on main.cpp
> +void task_1(int** ptr, size_t rows, size_t columns) {
done!

2022-10-27 14:10 UTC, Romanucci commented on main.cpp
> +        throw std::range_error("Only positive values!");
done!

2022-10-27 14:14 UTC, Romanucci commented on main.cpp
> +    std::cout << "2 - fill manual" << std::endl;
done!

2022-10-27 14:23 UTC, Romanucci commented on main.cpp
> +
done!

2022-10-27 14:45 UTC, MarinaPaley commented on main.cpp
> +    int n, m;
```cpp
size_t get_size(const std::string& message)
{
    int size = -1;
    std::cout << message;
    std::cin >> size;

    if (size < 0)
    {
        throw std::out_of_range("Incorrect size. Value has to be greater or equal zero.");
    }

    return size;
}
```

2022-10-27 14:45 UTC, MarinaPaley commented on main.cpp
> +        std::cout << "Type only '1' or '2'";
магия 🪄

2022-10-27 14:45 UTC, MarinaPaley commented on main.cpp
> +    if (rows <= 0 || columns <= 0) {
не достижимый код

2022-10-27 15:34 UTC, MarinaPaley approved these changes
Доделайте немного и `merge`

2022-10-27 15:34 UTC, MarinaPaley commented on main.cpp
> +};
документация

2022-10-27 15:34 UTC, MarinaPaley commented on main.cpp
> +
Зачем?

2022-10-27 15:34 UTC, MarinaPaley commented on main.cpp
> +            std::cout << "Type only '1' or '2'";
Опять не исправили магические константы

2022-10-27 16:56 UTC, Romanucci commented on main.cpp
> +};
done

2022-10-27 16:57 UTC, Romanucci commented on main.cpp
> +
done

2022-10-27 16:58 UTC, Romanucci commented on main.cpp
> +            std::cout << "Type only '1' or '2'";
done

2022-10-27 17:04 UTC, merged